// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI2026Demo.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalAPI2026Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811201113_001Intit")]
    partial class _001Intit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedSiteId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivatedById")
                        .HasColumnType("text");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RestoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RestoredById")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSiteId");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RestoredById");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustodyStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("DateDiscoveredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateSubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublicNarrative")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<DateTimeOffset?>("ShipmentReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipmentReceivedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ShipmentSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipmentSentById")
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TransferAuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferAuthorizedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TransferCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferCompletedById")
                        .HasColumnType("text");

                    b.Property<string>("TransferReason")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<DateTimeOffset?>("TransferRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferRequestedById")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedById")
                        .HasColumnType("text");

                    b.Property<string>("WarehouseLocation")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentReceivedById");

                    b.HasIndex("ShipmentSentById");

                    b.HasIndex("SiteId");

                    b.HasIndex("TransferAuthorizedById");

                    b.HasIndex("TransferCompletedById");

                    b.HasIndex("TransferRequestedById");

                    b.HasIndex("VerifiedById");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.ArtifactMediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtifactId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedById")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("VerifiedById");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.CatalogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtifactId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateSubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("CatalogRecords");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.CatalogRecordNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CatalogRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CatalogRecordId");

                    b.ToTable("CatalogNotes");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.DirectMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset?>("DeletedByRecipientAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedBySenderAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeletedByRecipient")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeletedBySender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ALRECNarrative")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosureAuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosureAuthorizedById")
                        .HasColumnType("text");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ClosureRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosureRequestedById")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublicNarrative")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedById")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClosedById");

                    b.HasIndex("ClosureAuthorizedById");

                    b.HasIndex("ClosureRequestedById");

                    b.HasIndex("VerifiedById");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.ApplicationUser", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.Site", "AssignedSite")
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("AssignedSiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "RestoredBy")
                        .WithMany()
                        .HasForeignKey("RestoredById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedSite");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("RestoredBy");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Artifact", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ShipmentReceivedBy")
                        .WithMany()
                        .HasForeignKey("ShipmentReceivedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ShipmentSentBy")
                        .WithMany()
                        .HasForeignKey("ShipmentSentById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.Site", "Site")
                        .WithMany("Artifacts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "TransferAuthorizedBy")
                        .WithMany()
                        .HasForeignKey("TransferAuthorizedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "TransferCompletedBy")
                        .WithMany()
                        .HasForeignKey("TransferCompletedById");

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "TransferRequestedBy")
                        .WithMany()
                        .HasForeignKey("TransferRequestedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ShipmentReceivedBy");

                    b.Navigation("ShipmentSentBy");

                    b.Navigation("Site");

                    b.Navigation("TransferAuthorizedBy");

                    b.Navigation("TransferCompletedBy");

                    b.Navigation("TransferRequestedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.ArtifactMediaFile", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.Artifact", "Artifact")
                        .WithMany("MediaFiles")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "UploadedBy")
                        .WithMany("UploadedMedia")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artifact");

                    b.Navigation("UploadedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.AuditLog", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ActorUser")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.CatalogRecord", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.Artifact", "Artifact")
                        .WithMany("CatalogRecords")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "SubmittedBy")
                        .WithMany("SubmittedCatalogRecords")
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.CatalogRecordNote", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "Author")
                        .WithMany("AuthoredCatalogNotes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.CatalogRecord", "CatalogRecord")
                        .WithMany("Notes")
                        .HasForeignKey("CatalogRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CatalogRecord");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.DirectMessage", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Site", b =>
                {
                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ClosedBy")
                        .WithMany()
                        .HasForeignKey("ClosedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ClosureAuthorizedBy")
                        .WithMany()
                        .HasForeignKey("ClosureAuthorizedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "ClosureRequestedBy")
                        .WithMany()
                        .HasForeignKey("ClosureRequestedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalAPI2026Demo.Models.ApplicationUser", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosedBy");

                    b.Navigation("ClosureAuthorizedBy");

                    b.Navigation("ClosureRequestedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.ApplicationUser", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("AuthoredCatalogNotes");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("SubmittedCatalogRecords");

                    b.Navigation("UploadedMedia");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Artifact", b =>
                {
                    b.Navigation("CatalogRecords");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.CatalogRecord", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MinimalAPI2026Demo.Models.Site", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("AssignedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
